[tool.ruff]
include = ["pyproject.toml", "src/**/*.py", "tests/**/*.py"]
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN",     # flake8-annotations
    "COM812",  # Trailing comma missing, conflicts with ruff format
    "D",       # pydocstyle
    "E501",    # Line too long
    "EM102",   # Exception must not use an f-string literal, assign to variable first
    "PLR2004", # Magic value used in comparison
    "S101",    # Use of `assert` detected
    "TRY003",  # Avoid specifying long messages outside the exception class
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "INP001",  # File is part of an implicit namespace package. Add an __init__.py.
    "PLR2004", # Magic value used in comparison
]

[tool.mypy]
ignore_missing_imports = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"  # test summary for (a)ll except passed
testpaths = ["tests"]
log_cli = true
log_cli_level = "WARNING"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = ruff, mypy, py37, py38, py39, py310, py311, py312, coverage-report

[testenv:ruff]
skip_install = true
deps = ruff
commands =
    ruff check .

[testenv:mypy]
skip_install = true
deps = mypy
commands =
    mypy src/

[testenv]
extras = tests
deps = toml
commands = 
    coverage run -m pytest

[testenv:coverage-report]
skip_install = true
deps =
    coverage[toml]>=5
commands =
    - coverage combine
    coverage report
    coverage xml

[testenv:docs]
extras = docs
changedir = docs
commands =
    sphinx-build -b linkcheck . _build
    sphinx-build -b dummy . _build
"""

[tool.coverage.run]
branch = true
source = ["weatherlink_live_local"]

[tool.coverage.paths]
source = ["src", "*/site-packages"]
