[tool.black]
line-length = 100

[tool.isort]
line_length = 100
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true

[tool.pylint.message_control]
disable = [
    "import-error",
    "bad-continuation",
    "missing-function-docstring",
    "logging-fstring-interpolation",
    "too-many-instance-attributes",
]

[tool.pylint.format]
max-line-length = 100
good-names = [
    "logger",
    "ip",
    "zc",
]

[tool.mypy]
ignore_missing_imports = true  # not supported yet

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"  # test summary for (a)ll except passed
testpaths = ["tests"]
log_cli = true
log_cli_level = "WARNING"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = black, isort, pylint, mypy, py36, py37, py38, py39, coverage-report

[testenv:black]
skip_install = true
deps = black
commands =
    black --diff src/
    black --check src/

[testenv:isort]
skip_install = true
deps = isort>5
commands =
    isort --diff src/
    isort --check-only src/

[testenv:pylint]
skip_install = true
deps = pylint
commands = pylint src/

[testenv:mypy]
skip_install = true
deps = mypy
commands = mypy --ignore-missing-imports src/

[testenv]
extras = tests
deps = toml
commands = 
    coverage run --parallel -m pytest

[testenv:coverage-report]
skip_install = true
deps =
    coverage>=5
    toml
commands =
    - coverage combine
    coverage report

[testenv:coveralls]
skip_install = true
deps =
    coverage>=5
    coveralls
    toml
passenv = GITHUB_*
commands = 
    - coverage combine
    coveralls

[testenv:docs]
extras = docs
changedir = docs
whitelist_externals = make
commands =
    make linkcheck
    make dummy
"""

[tool.coverage.run]
branch = true
source = ["weatherlink_live_local"]

[tool.coverage.paths]
source = ["src", ".tox/*/site-packages"]
