name: CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
        exclude:
          - { os: macos-latest, python: "3.7" } # not available for newer arm64 macos
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: pip install tox
      - name: Run ruff
        run: tox -e ruff
      - name: Run mypy
        run: tox -e mypy
      - name: Run pytest
        run: tox -e py
      - name: Coverage report
        run: tox -e coverage-report
      - name: Upload coverage results to Coveralls
        if: matrix.os == 'ubuntu-latest' && matrix.python == '3.12'
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage.xml

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install Tox
        run: pip install tox
      - name: Check docs
        run: tox -e docs
